# Site settings
title: Tale
email: wonyj12@gmail.com
description: Soukwon Jun's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: lonby

# Build settings
markdown: kramdown
